import { useEffect, useMemo, useState } from "react";
import { getHistoryData } from "../lib/backend";
import type { HistoryData } from "../lib/types";
import { formatMoney } from "../lib/money";

export function History() {
  const [data,setData]=useState<HistoryData|null>(null); const [error,setError]=useState(""); const [tab,setTab]=useState<"activity"|"payments"|"reconciliations">("activity"); const [search,setSearch]=useState("");
  useEffect(()=>{getHistoryData().then(setData).catch(e=>setError(e instanceof Error?e.message:String(e)))},[]);
  const filtered=useMemo(()=>{if(!data)return[];const q=search.toLowerCase().trim();if(tab==="activity")return data.activity.filter(x=>!q||`${x.summary} ${x.userName??""} ${x.eventType}`.toLowerCase().includes(q));if(tab==="payments")return data.payments.filter(x=>!q||`${x.billName} ${x.paidBy} ${x.note??""}`.toLowerCase().includes(q));return data.reconciliations.filter(x=>!q||`${x.accountName} ${x.performedBy??""}`.toLowerCase().includes(q))},[data,tab,search]);
  return <div className="page history-page"><header className="page-header"><div><h1>History</h1><p>Review payments, balance reconciliations, paycheck changes, and other important household activity.</p></div></header>{error&&<div className="page-error">{error}</div>}{!data?<div className="loading-inline">Loading history…</div>:<section className="card history-card"><div className="history-toolbar"><div className="segmented"><button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>Activity</button><button className={tab==="payments"?"active":""} onClick={()=>setTab("payments")}>Payments</button><button className={tab==="reconciliations"?"active":""} onClick={()=>setTab("reconciliations")}>Reconciliations</button></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search history…"/></div>{tab==="activity"?<ActivityTable items={filtered as HistoryData["activity"]}/>:tab==="payments"?<PaymentTable items={filtered as HistoryData["payments"]}/>:<ReconcileTable items={filtered as HistoryData["reconciliations"]}/>}</section>}</div>
}

function ActivityTable({items}:{items:HistoryData["activity"]}){return <div className="history-list">{items.length?items.map(x=><div className="history-item" key={x.id}><div className="history-icon">{icon(x.eventType)}</div><div><strong>{x.summary}</strong><span>{friendly(x.eventType)} • {x.userName??"Household"}</span></div><time>{formatDateTime(x.occurredAt)}</time></div>):<div className="empty-inline">No matching activity.</div>}</div>}
function PaymentTable({items}:{items:HistoryData["payments"]}){return <div><div className="history-table-head"><span>Date</span><span>Bill</span><span>Paid By</span><span>Amount</span><span>Note</span></div>{items.length?items.map(x=><div className="history-table-row" key={x.id}><span>{formatDate(x.paidDate)}</span><strong>{x.billName}</strong><span>{x.paidBy}</span><b>{formatMoney(x.amountCents)}</b><span>{x.note??"—"}</span></div>):<div className="empty-inline">No matching payments.</div>}</div>}
function ReconcileTable({items}:{items:HistoryData["reconciliations"]}){return <div><div className="history-table-head reconcile-history-head"><span>Date</span><span>Account</span><span>Before</span><span>Actual</span><span>Difference</span><span>By</span></div>{items.length?items.map(x=><div className="history-table-row reconcile-history-row" key={x.id}><span>{formatDateTime(x.performedAt)}</span><strong>{x.accountName}</strong><span>{formatMoney(x.beforeCents)}</span><span>{formatMoney(x.actualCents)}</span><b className={x.differenceCents<0?"negative-money":x.differenceCents>0?"positive-money":""}>{formatMoney(x.differenceCents)}</b><span>{x.performedBy??"Household"}</span></div>):<div className="empty-inline">No balance reconciliations yet.</div>}</div>}
function icon(v:string){if(v.includes("payment"))return"✓";if(v.includes("paycheck"))return"＄";if(v.includes("reconcil"))return"↻";if(v.includes("bill"))return"▣";return"•"}
function friendly(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function formatDate(v:string){return new Date(`${v}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}
function formatDateTime(v:string){const d=new Date(v.includes("T")?v:v.replace(" ","T"));return Number.isNaN(d.getTime())?v:d.toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})}
